type Customer {
    name: String
    id: String
}

type BusinessService{
    nameOfService: String
    priceOfService: Float
    descriptionOfService: String
    timeOfService: String
}

type Business{
    business_entity_id: Int
    business_user_id: Int
    name: String
    phone: String
    email: String
    businessService: [BusinessService]
}

type Query{
    getBusinesses:[Business]
}



schema{
    query: Query
}